version: '3.9'
services:
  test: &base
    build:
      context: ./
      target: dev
    image: kuala-test
    command: go test -v ./...
    volumes:
      - .:/go/src/github.com/michelsazevedo/kuala/
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_USER=kuala
      - POSTGRES_PASSWORD=kualapwd
      - POSTGRES_DB=kuala
      - POSTGRES_HOST=db:5432

  web:
    <<: *base
    image: kuala_web
    command: go run .
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kuala
      - POSTGRES_PASSWORD=kualapwd
      - POSTGRES_DB=kuala
      

volumes:
  db_data:
